name: Test0620
on: push

jobs:
  test-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: first 
      run: |
        pip3 install -r requirements.txt
    - name: onedata
      run: |
        python3 0609-2.py > log.txt 2>&1 &
    - name: twodata
      run: |
        python3 0609-4.py > log.txt 2>&1 &
